name: Website Deployment e-commerce 1

# Controls when the workflow will run
on:
  # Triggers the workflow every 15 minutes
  schedule:
    - cron: "*/200 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Run a command to make an HTTP request to your website
      - name: Ping Website
        run: curl -sS -I https://mern-ecommerce-u3eu.onrender.com

      # Optionally, you can add more steps here like running tests, etc.
